// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartField.Domain.Enums;
using SmartField.Infrastructure.Persistence;

#nullable disable

namespace SmartField.Infrastructure.Persistence.Migrations;

[DbContext(typeof(SmartFieldDbContext))]
[Migration("20260828123000_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartField.Domain.Entities.AttendanceCorrection", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("AttendanceEventId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CorrectedTimestampUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<AttendanceEventType>("CorrectedEventType")
                    .HasConversion<string>()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<Guid>("CorrectedByUserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<AttendanceEventType>("OriginalEventType")
                    .HasConversion<string>()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTimeOffset>("OriginalTimestampUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.HasKey("Id");

                b.HasIndex("AttendanceEventId");

                b.HasIndex("CompanyId");

                b.ToTable("AttendanceCorrections");
            });

            modelBuilder.Entity("SmartField.Domain.Entities.AttendanceEvent", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ClientEventId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset?>("ClientTimestampUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<decimal?>("DistanceFromWorkSiteMeters")
                    .HasPrecision(10, 2)
                    .HasColumnType("decimal(10,2)");

                b.Property<Guid>("EmployeeId")
                    .HasColumnType("uniqueidentifier");

                b.Property<AttendanceEventType>("EventType")
                    .HasConversion<string>()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<bool?>("IsInsideGeofence")
                    .HasColumnType("bit");

                b.Property<decimal?>("Latitude")
                    .HasPrecision(9, 6)
                    .HasColumnType("decimal(9,6)");

                b.Property<decimal?>("LocationAccuracyMeters")
                    .HasPrecision(10, 2)
                    .HasColumnType("decimal(10,2)");

                b.Property<decimal?>("Longitude")
                    .HasPrecision(9, 6)
                    .HasColumnType("decimal(9,6)");

                b.Property<string>("Notes")
                    .HasMaxLength(1000)
                    .HasColumnType("nvarchar(1000)");

                b.Property<Guid?>("ProjectId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("ServerTimestampUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<AttendanceSource>("Source")
                    .HasConversion<string>()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<Guid?>("WorkSiteId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("ClientEventId")
                    .IsUnique();

                b.HasIndex("EmployeeId");

                b.HasIndex("ProjectId");

                b.HasIndex("WorkSiteId");

                b.HasIndex("CompanyId", "EmployeeId", "ServerTimestampUtc");

                b.ToTable("AttendanceEvents");
            });

            modelBuilder.Entity("SmartField.Domain.Entities.AuditLog", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid>("EntityId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("EntityType")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("NewValues")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("OldValues")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset>("TimestampUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("CompanyId", "EntityType", "EntityId");

                b.ToTable("AuditLogs");
            });

            modelBuilder.Entity("SmartField.Domain.Entities.Company", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("Nif")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("TimeZone")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.ToTable("Companies");

                b.HasData(new
                {
                    Id = Guid.Parse("9f0b4a28-864b-4d2f-9ca6-44cf64352d68"),
                    Code = "SYS-DEMO",
                    CreatedAtUtc = new DateTimeOffset(2026, 8, 27, 0, 0, 0, TimeSpan.Zero),
                    IsActive = true,
                    Name = "SmartField Demo",
                    Nif = string.Empty,
                    TimeZone = "Europe/Lisbon"
                });
            });

            modelBuilder.Entity("SmartField.Domain.Entities.CompanySettings", b =>
            {
                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<bool>("AllowBreaks")
                    .HasColumnType("bit");

                b.Property<bool>("AllowProjectSelection")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<int>("DefaultGeofenceRadiusMeters")
                    .HasColumnType("int");

                b.Property<GeofenceMode>("GeofenceMode")
                    .HasColumnType("int");

                b.Property<bool>("RequireGeolocation")
                    .HasColumnType("bit");

                b.Property<bool>("RequireProjectSelection")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("CompanyId");

                b.ToTable("CompanySettings");

                b.HasData(new
                {
                    CompanyId = Guid.Parse("9f0b4a28-864b-4d2f-9ca6-44cf64352d68"),
                    AllowBreaks = true,
                    AllowProjectSelection = false,
                    CreatedAtUtc = new DateTimeOffset(2026, 8, 27, 0, 0, 0, TimeSpan.Zero),
                    DefaultGeofenceRadiusMeters = 100,
                    GeofenceMode = GeofenceMode.Disabled,
                    RequireGeolocation = false,
                    RequireProjectSelection = false
                });
            });

            modelBuilder.Entity("SmartField.Domain.Entities.Employee", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("DefaultWorkSiteId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Email")
                    .HasMaxLength(320)
                    .HasColumnType("nvarchar(320)");

                b.Property<string>("EmployeeNumber")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("ErpEmployeeCode")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ExternalId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ExternalSystem")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("MobilePhone")
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("DefaultWorkSiteId");

                b.HasIndex("CompanyId", "EmployeeNumber")
                    .IsUnique();

                b.ToTable("Employees");

                b.HasData(new
                {
                    Id = Guid.Parse("49f8a4ab-9802-46a4-99d7-2bcd6a664ad8"),
                    CompanyId = Guid.Parse("9f0b4a28-864b-4d2f-9ca6-44cf64352d68"),
                    CreatedAtUtc = new DateTimeOffset(2026, 8, 27, 0, 0, 0, TimeSpan.Zero),
                    EmployeeNumber = "FUNC001",
                    IsActive = true,
                    Name = "Funcionário Demo"
                });
            });

            modelBuilder.Entity("SmartField.Domain.Entities.ExternalReference", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("EntityType")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ExternalCode")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ExternalEntityId")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<Guid>("LocalEntityId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("SystemName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("CompanyId", "SystemName", "EntityType", "LocalEntityId");

                b.ToTable("ExternalReferences");
            });

            modelBuilder.Entity("SmartField.Domain.Entities.IntegrationOutbox", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<int>("AttemptCount")
                    .HasColumnType("int");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid>("EntityId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("EntityType")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<string>("EventType")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTimeOffset?>("LastAttemptUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("LastError")
                    .HasMaxLength(2000)
                    .HasColumnType("nvarchar(2000)");

                b.Property<string>("Payload")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset?>("ProcessedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<IntegrationStatus>("Status")
                    .ValueGeneratedOnAdd()
                    .HasConversion<string>()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue(IntegrationStatus.Pending);

                b.HasKey("Id");

                b.HasIndex("CompanyId", "Status", "CreatedAtUtc");

                b.ToTable("IntegrationOutbox");
            });

            modelBuilder.Entity("SmartField.Domain.Entities.Project", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("CustomerName")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateOnly?>("EndDate")
                    .HasColumnType("date");

                b.Property<string>("ErpCostCenterCode")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ErpProjectCode")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ExternalId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ExternalSystem")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<ProjectType>("ProjectType")
                    .ValueGeneratedOnAdd()
                    .HasConversion<string>()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue(ProjectType.Other);

                b.Property<DateOnly?>("StartDate")
                    .HasColumnType("date");

                b.Property<ProjectStatus>("Status")
                    .ValueGeneratedOnAdd()
                    .HasConversion<string>()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)")
                    .HasDefaultValue(ProjectStatus.Draft);

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("WorkSiteId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("WorkSiteId");

                b.HasIndex("CompanyId", "Code")
                    .IsUnique();

                b.ToTable("Projects");
            });

            modelBuilder.Entity("SmartField.Domain.Entities.WorkSite", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Address")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<Guid>("CompanyId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("ErpCostCenterCode")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ExternalId")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("ExternalSystem")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int?>("GeofenceRadiusMeters")
                    .HasColumnType("int");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<decimal?>("Latitude")
                    .HasPrecision(9, 6)
                    .HasColumnType("decimal(9,6)");

                b.Property<decimal?>("Longitude")
                    .HasPrecision(9, 6)
                    .HasColumnType("decimal(9,6)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTimeOffset?>("UpdatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("CompanyId", "Code")
                    .IsUnique();

                b.ToTable("WorkSites");
            });

            modelBuilder.Entity("SmartField.Domain.Entities.AttendanceCorrection", b =>
            {
                b.HasOne("SmartField.Domain.Entities.AttendanceEvent", null)
                    .WithMany()
                    .HasForeignKey("AttendanceEventId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SmartField.Domain.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("SmartField.Domain.Entities.AttendanceEvent", b =>
            {
                b.HasOne("SmartField.Domain.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SmartField.Domain.Entities.Employee", null)
                    .WithMany()
                    .HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SmartField.Domain.Entities.Project", null)
                    .WithMany()
                    .HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("SmartField.Domain.Entities.WorkSite", null)
                    .WithMany()
                    .HasForeignKey("WorkSiteId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("SmartField.Domain.Entities.AuditLog", b =>
            {
                b.HasOne("SmartField.Domain.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("SmartField.Domain.Entities.CompanySettings", b =>
            {
                b.HasOne("SmartField.Domain.Entities.Company", null)
                    .WithOne()
                    .HasForeignKey("SmartField.Domain.Entities.CompanySettings", "CompanyId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("SmartField.Domain.Entities.Employee", b =>
            {
                b.HasOne("SmartField.Domain.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SmartField.Domain.Entities.WorkSite", null)
                    .WithMany()
                    .HasForeignKey("DefaultWorkSiteId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("SmartField.Domain.Entities.ExternalReference", b =>
            {
                b.HasOne("SmartField.Domain.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("SmartField.Domain.Entities.IntegrationOutbox", b =>
            {
                b.HasOne("SmartField.Domain.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });

            modelBuilder.Entity("SmartField.Domain.Entities.Project", b =>
            {
                b.HasOne("SmartField.Domain.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SmartField.Domain.Entities.WorkSite", null)
                    .WithMany()
                    .HasForeignKey("WorkSiteId")
                    .OnDelete(DeleteBehavior.Restrict);
            });

            modelBuilder.Entity("SmartField.Domain.Entities.WorkSite", b =>
            {
                b.HasOne("SmartField.Domain.Entities.Company", null)
                    .WithMany()
                    .HasForeignKey("CompanyId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
            });
#pragma warning restore 612, 618
    }
}
